### ISSUE TITLE
server side implementation 

### ISSUE THREAD

**Issue by WaseemSammy** [saveendhiman/XMPPSample-Eclipse#1]
please solve my issue 

i have host ip ,username ,password 

i have seen in code 

public static final String LIVESERVICE = "liveappgroup@liveapp." + HOST;

```
public static final int PORT = 5222;
```

in this what is   liveappgroup@liveapp.

**Comment by saveendhiman** [comment]
hi, i have answered in youtube as well.

You have to pass host ip as your server name and username and password is for users that you created in openfire. Try to check code and youtube video how it work.

thanks
